Added XSS injection Attack Using SVG Images
crowdsecurity/sec-lists pull request #25
Opened 2022-01-28 21:03 UTC by rhoekman

2022-04-19 13:10 UTC, he2ss requested changes
Adding also `%3Csvg` to be consistent with other rules.

2022-04-26 16:28 UTC, AlteredCoder commented
@rhoekman Can you add the `%3Csvg` into this pull request so we can merge it please ? :)

2022-10-04 09:32 UTC, LaurenceJJones approved these changes
Changes were added, LGTM

2022-10-04 09:32 UTC, LaurenceJJones approved these changes

2022-10-04 10:49 UTC, merged